version: "3.9"

services:
  conside:
    hostname: conside-api
    image: conside:latest
    restart: unless-stopped
    build:
      context: ../src
      dockerfile: Consid.Logger.Host/Dockerfile
    # MacOS and Linux 
    volumes:
      - ${HOME}/.aspnet/https:/https/
    # Windows 
    #volumes:
    # - %USERPROFILE%\.aspnet\https:/https/
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" # Development | Release
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ""
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
  
